<?php defined('SYSPATH') OR die('No direct script access.');

class Migration_App_20180322122225 extends Minion_Migration_Base
{

    /**
     * Run queries needed to apply this migration
     *
     * @param Kohana_Database $db Database connection
     */
    public function up(Kohana_Database $db)
    {
        $db->query(NULL, 'CREATE TABLE `countries` (
  `id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `code` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8');

        $db->query(Database::INSERT,'INSERT INTO `countries` (`id`, `name`, `code`) VALUES
	(1, \'Andorra\', \'AD\'),
	(2, \'United Arab Emirates\', \'AE\'),
	(3, \'Afghanistan\', \'AF\'),
	(4, \'Antigua and Barbuda\', \'AG\'),
	(5, \'Anguilla\', \'AI\'),
	(6, \'Albania\', \'AL\'),
	(7, \'Armenia\', \'AM\'),
	(8, \'Angola\', \'AO\'),
	(9, \'Antarctica\', \'AQ\'),
	(10, \'Argentina\', \'AR\'),
	(11, \'American Samoa\', \'AS\'),
	(12, \'Austria\', \'AT\'),
	(13, \'Australia\', \'AU\'),
	(14, \'Aruba\', \'AW\'),
	(15, \'Åland\', \'AX\'),
	(16, \'Azerbaijan\', \'AZ\'),
	(17, \'Bosnia and Herzegovina\', \'BA\'),
	(18, \'Barbados\', \'BB\'),
	(19, \'Bangladesh\', \'BD\'),
	(20, \'Belgium\', \'BE\'),
	(21, \'Burkina Faso\', \'BF\'),
	(22, \'Bulgaria\', \'BG\'),
	(23, \'Bahrain\', \'BH\'),
	(24, \'Burundi\', \'BI\'),
	(25, \'Benin\', \'BJ\'),
	(26, \'Saint Barthélemy\', \'BL\'),
	(27, \'Bermuda\', \'BM\'),
	(28, \'Brunei\', \'BN\'),
	(29, \'Bolivia\', \'BO\'),
	(30, \'Bonaire\', \'BQ\'),
	(31, \'Brazil\', \'BR\'),
	(32, \'Bahamas\', \'BS\'),
	(33, \'Bhutan\', \'BT\'),
	(34, \'Bouvet Island\', \'BV\'),
	(35, \'Botswana\', \'BW\'),
	(36, \'Belarus\', \'BY\'),
	(37, \'Belize\', \'BZ\'),
	(38, \'Canada\', \'CA\'),
	(39, \'Cocos [Keeling] Islands\', \'CC\'),
	(40, \'Democratic Republic of the Congo\', \'CD\'),
	(41, \'Central African Republic\', \'CF\'),
	(42, \'Republic of the Congo\', \'CG\'),
	(43, \'Switzerland\', \'CH\'),
	(44, \'Ivory Coast\', \'CI\'),
	(45, \'Cook Islands\', \'CK\'),
	(46, \'Chile\', \'CL\'),
	(47, \'Cameroon\', \'CM\'),
	(48, \'China\', \'CN\'),
	(49, \'Colombia\', \'CO\'),
	(50, \'Costa Rica\', \'CR\'),
	(51, \'Cuba\', \'CU\'),
	(52, \'Cape Verde\', \'CV\'),
	(53, \'Curacao\', \'CW\'),
	(54, \'Christmas Island\', \'CX\'),
	(55, \'Cyprus\', \'CY\'),
	(56, \'Czech Republic\', \'CZ\'),
	(57, \'Germany\', \'DE\'),
	(58, \'Djibouti\', \'DJ\'),
	(59, \'Denmark\', \'DK\'),
	(60, \'Dominica\', \'DM\'),
	(61, \'Dominican Republic\', \'DO\'),
	(62, \'Algeria\', \'DZ\'),
	(63, \'Ecuador\', \'EC\'),
	(64, \'Estonia\', \'EE\'),
	(65, \'Egypt\', \'EG\'),
	(66, \'Western Sahara\', \'EH\'),
	(67, \'Eritrea\', \'ER\'),
	(68, \'Spain\', \'ES\'),
	(69, \'Ethiopia\', \'ET\'),
	(70, \'Finland\', \'FI\'),
	(71, \'Fiji\', \'FJ\'),
	(72, \'Falkland Islands\', \'FK\'),
	(73, \'Micronesia\', \'FM\'),
	(74, \'Faroe Islands\', \'FO\'),
	(75, \'France\', \'FR\'),
	(76, \'Gabon\', \'GA\'),
	(77, \'United Kingdom\', \'GB\'),
	(78, \'Grenada\', \'GD\'),
	(79, \'Georgia\', \'GE\'),
	(80, \'French Guiana\', \'GF\'),
	(81, \'Guernsey\', \'GG\'),
	(82, \'Ghana\', \'GH\'),
	(83, \'Gibraltar\', \'GI\'),
	(84, \'Greenland\', \'GL\'),
	(85, \'Gambia\', \'GM\'),
	(86, \'Guinea\', \'GN\'),
	(87, \'Guadeloupe\', \'GP\'),
	(88, \'Equatorial Guinea\', \'GQ\'),
	(89, \'Greece\', \'GR\'),
	(90, \'South Georgia and the South Sandwich Islands\', \'GS\'),
	(91, \'Guatemala\', \'GT\'),
	(92, \'Guam\', \'GU\'),
	(93, \'Guinea-Bissau\', \'GW\'),
	(94, \'Guyana\', \'GY\'),
	(95, \'Hong Kong\', \'HK\'),
	(96, \'Heard Island and McDonald Islands\', \'HM\'),
	(97, \'Honduras\', \'HN\'),
	(98, \'Croatia\', \'HR\'),
	(99, \'Haiti\', \'HT\'),
	(100, \'Hungary\', \'HU\'),
	(101, \'Indonesia\', \'ID\'),
	(102, \'Ireland\', \'IE\'),
	(103, \'Israel\', \'IL\'),
	(104, \'Isle of Man\', \'IM\'),
	(105, \'India\', \'IN\'),
	(106, \'British Indian Ocean Territory\', \'IO\'),
	(107, \'Iraq\', \'IQ\'),
	(108, \'Iran\', \'IR\'),
	(109, \'Iceland\', \'IS\'),
	(110, \'Italy\', \'IT\'),
	(111, \'Jersey\', \'JE\'),
	(112, \'Jamaica\', \'JM\'),
	(113, \'Jordan\', \'JO\'),
	(114, \'Japan\', \'JP\'),
	(115, \'Kenya\', \'KE\'),
	(116, \'Kyrgyzstan\', \'KG\'),
	(117, \'Cambodia\', \'KH\'),
	(118, \'Kiribati\', \'KI\'),
	(119, \'Comoros\', \'KM\'),
	(120, \'Saint Kitts and Nevis\', \'KN\'),
	(121, \'North Korea\', \'KP\'),
	(122, \'South Korea\', \'KR\'),
	(123, \'Kuwait\', \'KW\'),
	(124, \'Cayman Islands\', \'KY\'),
	(125, \'Kazakhstan\', \'KZ\'),
	(126, \'Laos\', \'LA\'),
	(127, \'Lebanon\', \'LB\'),
	(128, \'Saint Lucia\', \'LC\'),
	(129, \'Liechtenstein\', \'LI\'),
	(130, \'Sri Lanka\', \'LK\'),
	(131, \'Liberia\', \'LR\'),
	(132, \'Lesotho\', \'LS\'),
	(133, \'Lithuania\', \'LT\'),
	(134, \'Luxembourg\', \'LU\'),
	(135, \'Latvia\', \'LV\'),
	(136, \'Libya\', \'LY\'),
	(137, \'Morocco\', \'MA\'),
	(138, \'Monaco\', \'MC\'),
	(139, \'Moldova\', \'MD\'),
	(140, \'Montenegro\', \'ME\'),
	(141, \'Saint Martin\', \'MF\'),
	(142, \'Madagascar\', \'MG\'),
	(143, \'Marshall Islands\', \'MH\'),
	(144, \'Macedonia\', \'MK\'),
	(145, \'Mali\', \'ML\'),
	(146, \'Myanmar [Burma]\', \'MM\'),
	(147, \'Mongolia\', \'MN\'),
	(148, \'Macao\', \'MO\'),
	(149, \'Northern Mariana Islands\', \'MP\'),
	(150, \'Martinique\', \'MQ\'),
	(151, \'Mauritania\', \'MR\'),
	(152, \'Montserrat\', \'MS\'),
	(153, \'Malta\', \'MT\'),
	(154, \'Mauritius\', \'MU\'),
	(155, \'Maldives\', \'MV\'),
	(156, \'Malawi\', \'MW\'),
	(157, \'Mexico\', \'MX\'),
	(158, \'Malaysia\', \'MY\'),
	(159, \'Mozambique\', \'MZ\'),
	(160, \'Namibia\', \'NA\'),
	(161, \'New Caledonia\', \'NC\'),
	(162, \'Niger\', \'NE\'),
	(163, \'Norfolk Island\', \'NF\'),
	(164, \'Nigeria\', \'NG\'),
	(165, \'Nicaragua\', \'NI\'),
	(166, \'Netherlands\', \'NL\'),
	(167, \'Norway\', \'NO\'),
	(168, \'Nepal\', \'NP\'),
	(169, \'Nauru\', \'NR\'),
	(170, \'Niue\', \'NU\'),
	(171, \'New Zealand\', \'NZ\'),
	(172, \'Oman\', \'OM\'),
	(173, \'Panama\', \'PA\'),
	(174, \'Peru\', \'PE\'),
	(175, \'French Polynesia\', \'PF\'),
	(176, \'Papua New Guinea\', \'PG\'),
	(177, \'Philippines\', \'PH\'),
	(178, \'Pakistan\', \'PK\'),
	(179, \'Poland\', \'PL\'),
	(180, \'Saint Pierre and Miquelon\', \'PM\'),
	(181, \'Pitcairn Islands\', \'PN\'),
	(182, \'Puerto Rico\', \'PR\'),
	(183, \'Palestine\', \'PS\'),
	(184, \'Portugal\', \'PT\'),
	(185, \'Palau\', \'PW\'),
	(186, \'Paraguay\', \'PY\'),
	(187, \'Qatar\', \'QA\'),
	(188, \'Réunion\', \'RE\'),
	(189, \'Romania\', \'RO\'),
	(190, \'Serbia\', \'RS\'),
	(191, \'Russia\', \'RU\'),
	(192, \'Rwanda\', \'RW\'),
	(193, \'Saudi Arabia\', \'SA\'),
	(194, \'Solomon Islands\', \'SB\'),
	(195, \'Seychelles\', \'SC\'),
	(196, \'Sudan\', \'SD\'),
	(197, \'Sweden\', \'SE\'),
	(198, \'Singapore\', \'SG\'),
	(199, \'Saint Helena\', \'SH\'),
	(200, \'Slovenia\', \'SI\'),
	(201, \'Svalbard and Jan Mayen\', \'SJ\'),
	(202, \'Slovakia\', \'SK\'),
	(203, \'Sierra Leone\', \'SL\'),
	(204, \'San Marino\', \'SM\'),
	(205, \'Senegal\', \'SN\'),
	(206, \'Somalia\', \'SO\'),
	(207, \'Suriname\', \'SR\'),
	(208, \'South Sudan\', \'SS\'),
	(209, \'São Tomé and Príncipe\', \'ST\'),
	(210, \'El Salvador\', \'SV\'),
	(211, \'Sint Maarten\', \'SX\'),
	(212, \'Syria\', \'SY\'),
	(213, \'Swaziland\', \'SZ\'),
	(214, \'Turks and Caicos Islands\', \'TC\'),
	(215, \'Chad\', \'TD\'),
	(216, \'French Southern Territories\', \'TF\'),
	(217, \'Togo\', \'TG\'),
	(218, \'Thailand\', \'TH\'),
	(219, \'Tajikistan\', \'TJ\'),
	(220, \'Tokelau\', \'TK\'),
	(221, \'East Timor\', \'TL\'),
	(222, \'Turkmenistan\', \'TM\'),
	(223, \'Tunisia\', \'TN\'),
	(224, \'Tonga\', \'TO\'),
	(225, \'Turkey\', \'TR\'),
	(226, \'Trinidad and Tobago\', \'TT\'),
	(227, \'Tuvalu\', \'TV\'),
	(228, \'Taiwan\', \'TW\'),
	(229, \'Tanzania\', \'TZ\'),
	(230, \'Ukraine\', \'UA\'),
	(231, \'Uganda\', \'UG\'),
	(232, \'U.S. Minor Outlying Islands\', \'UM\'),
	(233, \'United States\', \'US\'),
	(234, \'Uruguay\', \'UY\'),
	(235, \'Uzbekistan\', \'UZ\'),
	(236, \'Vatican City\', \'VA\'),
	(237, \'Saint Vincent and the Grenadines\', \'VC\'),
	(238, \'Venezuela\', \'VE\'),
	(239, \'British Virgin Islands\', \'VG\'),
	(240, \'U.S. Virgin Islands\', \'VI\'),
	(241, \'Vietnam\', \'VN\'),
	(242, \'Vanuatu\', \'VU\'),
	(243, \'Wallis and Futuna\', \'WF\'),
	(244, \'Samoa\', \'WS\'),
	(245, \'Kosovo\', \'XK\'),
	(246, \'Yemen\', \'YE\'),
	(247, \'Mayotte\', \'YT\'),
	(248, \'South Africa\', \'ZA\'),
	(249, \'Zambia\', \'ZM\'),
	(250, \'Zimbabwe\', \'ZW\');');
    }

    /**
     * Run queries needed to remove this migration
     *
     * @param Kohana_Database $db Database connection
     */
    public function down(Kohana_Database $db)
    {
        $db->query(NULL, 'DROP TABLE `countries`');
    }

}
